name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0

